
server:
  port: 8087


# 注册中心
eureka:
  port: 1111
  host: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.host}:${eureka.port}/eureka/

spring:
  application:
    name: sop-auth

  cloud:
    zookeeper:
      connect-string: localhost:2181

  # 数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sop?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root

  thymeleaf:
    cache: false

logging:
  level:
    com:
      gitee: debug